board:
  init_nsvtor: 0x000000

interrupt:
  mode: disabled
  trigger:
    on-infinite-sleep: false
    interval: 1000
    custom:
      - name: idle_interrupt
        symbol: arch_cpu_idle
      - name: atomic_interrupt
        symbol: arch_cpu_atomic_idle
  # there is a offset of 0x10 for the isrtable in binary ninja and the real offset, need to + 0x10
  # allowlist:
  #   - 0x10
  #   - 0x16
  #   - 0x1b
  #   - 0x1c
  #   - 0x1d
  #   - 0x21
  #   - 0x28


memory_maps:
  - name: mmio
    address: 0x40000000
    size: 0x20000000
    type: mmio
  - name: ram
    address: 0x20000000
    size: 0x100000
    type: ram
  - name: text
    address: 0x0000000
    size: 0x20000000
    type: rom
    file:
      path: zephyr.bin


debug_hooks:
  - symbol: printk
    type: printf
  - symbol: assert_print
    type: printf
  - symbol: vprintk
    type: sprintf
    
exit_hooks:
  - name: z_do_kernel_oops
    symbol: z_do_kernel_oops
  - name: z_fatal_error
    symbol: z_fatal_error
  - name: z_arm_fault
    symbol: z_arm_fault

symbols:
  - zephyr.elf