cargo-features = ["profile-rustflags"]

[workspace]
resolver = "2"
members = [
    ".git-hooks",
    "archive",
    "common",
    "emulator",
    "frametracer",
    "fuzzer",
    "hoedur",
    "hoedur-analyze",
    "modeling",
    "qemu-build",
    "qemu-rs",
    "qemu-sys", "radio",
    "scripts/test_python_rust", "scripts/test_rust", "scripts/unix_socket"]

[profile.release]
# codegen-units = 1
# opt-level = 3
opt-level = 1
# lto = true
rustflags = ["-C", "linker=clang", "-C", "link-arg=-fuse-ld=lld"]
